#!/bin/sh
# postinst script for nexus
#
# see: dh_installdeb(1)

set -e

case "$1" in
    configure)

        # Create nexus group and user if it doesn't exist.
	if ! getent group | grep -q  -e '^nexus' ; then
            addgroup --system nexus
	fi

        if ! id nexus > /dev/null 2>&1 ; then
            adduser --system --home /var/lib/nexus --no-create-home \
                --ingroup nexus --disabled-password --shell /bin/bash \
                nexus
        fi

        # set directory permissions
        chown -R nexus:nexus /var/lib/nexus
        chown -R nexus:nexus /var/run/nexus
        chown -R nexus:nexus /var/log/nexus

    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
