#!/bin/sh
# postinst script for nexus
#
# see: dh_installdeb(1)

set -e

case "$1" in
    configure)

        # Create nexus user if it doesn't exist.
        if ! id nexus > /dev/null 2>&1 ; then
            adduser --system --home /var/lib/nexus --no-create-home \
                --ingroup nogroup --disabled-password --shell /bin/bash \
                nexus
        fi

        # set file permissions
        chown -R nexus.nogroup /var/lib/nexus /var/run/nexus /var/log/nexus
        chown -R nexus.nogroup /opt/nexus/logs /opt/nexus/tmp

    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0



